
// AUTH
export const CHANGE_AUTH_STATE = 'CHANGE_AUTH_STATE'

// POSTS
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const PATCH_POST_REQUEST = 'PATCH_POST_REQUEST'
export const PATCH_POST_SUCCESS = 'PATCH_POST_SUCCESS'

// USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

// COMMENTS
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'

// SCREENS
export const SET_PROFILE_SCREEN_USER_ID = 'SET_PROFILE_SCREEN_USER_ID'
